// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MysportShop.Models;

namespace MysportShop.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20231020180043_Use corectly")]
    partial class Usecorectly
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MysportShop.Models.MyProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categories");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("InfoWithProduct");

                    b.Property<string>("NameProduct");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("MyProduct");
                });

            modelBuilder.Entity("MysportShop.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BuyProductId");

                    b.Property<string>("Name");

                    b.Property<int>("Number");

                    b.Property<decimal>("TotalOrderSumma");

                    b.HasKey("id");

                    b.HasIndex("BuyProductId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MysportShop.Models.BuyProduct", b =>
                {
                    b.HasBaseType("MysportShop.Models.MyProduct");

                    b.Property<int>("Quantity");

                    b.Property<decimal>("SummaOnsetProduct");

                    b.HasDiscriminator().HasValue("BuyProduct");
                });

            modelBuilder.Entity("MysportShop.Models.Order", b =>
                {
                    b.HasOne("MysportShop.Models.BuyProduct", "BuyProduct")
                        .WithMany()
                        .HasForeignKey("BuyProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
